### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Auroracccc** [ycq091044/BIOT#2]
Dear author,is the dataset used in your code testing the official test dataset provided by the dataset creators? If not, could you please provide the test dataset used for code testing

**Comment by ycq091044** [comment]
The links to datasets are in the repo. Some datasets need to be requested on their websites.

**Comment by Auroracccc** [comment]
Dear author, how can I directly run the testing code to obtain the accuracy as reported in the paper without training the model? Is there any available test code for this?

**Comment by Auroracccc** [comment]
it remind me 
load pretrain model from /home/ubuntu/MyFiles/BIOT-main/pretrained-models/EEG-PREST-16-channels.ckpt
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

Restoring states from the checkpoint path at /home/ubuntu/MyFiles/BIOT-main/pretrained-models/EEG-PREST-16-channels.ckpt
Traceback (most recent call last):
  File "/home/ubuntu/MyFiles/BIOT-main/run_multiclass_supervised.py", line 353, in <module>
    supervised(args)
  File "/home/ubuntu/MyFiles/BIOT-main/run_multiclass_supervised.py", line 309, in supervised
    pretrain_result = trainer.test(
  File "/home/ubuntu/miniconda3/envs/py39-cu116/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 938, in test
    return self._call_and_handle_interrupt(self._test_impl, model, dataloaders, ckpt_path, verbose, datamodule)
  File "/home/ubuntu/miniconda3/envs/py39-cu116/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py39-cu116/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/py39-cu116/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _test_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ubuntu/miniconda3/envs/py39-cu116/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1179, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home/ubuntu/miniconda3/envs/py39-cu116/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1141, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/home/ubuntu/miniconda3/envs/py39-cu116/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 179, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/ubuntu/miniconda3/envs/py39-cu116/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 319, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
KeyError: 'state_dict'
how can i solve this problem

**Comment by Auroracccc** [comment]
> The links to datasets are in the repo. Some datasets need to be requested on their websites.

**Comment by ycq091044** [comment]
Sorry to reply late. We have not provided the individual pretrained model for each task yet. Working on it. But we do have provided three EEG pre-trained models.
